export enum UserActionTypes {
  REGISTER_REQUEST = "REGISTER_REQUEST",
  REGISTER_SUCCESS = "REGISTER_SUCCESS",
  REGISTER_FAIL = "REGISTER_FAIL",
  LOGIN_REQUEST = "LOGIN_REQUEST",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAIL = "LOGIN_FAIL",
  LOGOUT = "LOGOUT",
  LOAD_USER = "LOAD_USER",
  USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST",
  USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS",
  USER_UPDATE_FAIL = "USER_UPDATE_FAIL",
}

export enum AdminActionTypes {
  ADMIN_CREATE_USER_REQUEST = "ADMIN_CREATE_USER_REQUEST",
  ADMIN_CREATE_USER_SUCCESS = "ADMIN_CREATE_USER_SUCCESS",
  ADMIN_CREATE_USER_FAIL = "ADMIN_CREATE_USER_FAIL",
  ADMIN_GET_USERS_REQUEST = "ADMIN_GET_USERS_REQUEST",
  ADMIN_GET_USERS_SUCCESS = "ADMIN_GET_USERS_SUCCESS",
  ADMIN_GET_USERS_FAIL = "ADMIN_GET_USERS_FAIL",
  ADMIN_UPDATE_USER_REQUEST = "ADMIN_UPDATE_USER_REQUEST",
  ADMIN_UPDATE_USER_SUCCESS = "ADMIN_UPDATE_USER_SUCCESS",
  ADMIN_UPDATE_USER_FAIL = "ADMIN_UPDATE_USER_FAIL",
  ADMIN_DELETE_USER_REQUEST = "ADMIN_DELETE_USER_REQUEST",
  ADMIN_DELETE_USER_SUCCESS = "ADMIN_DELETE_USER_SUCCESS",
  ADMIN_DELETE_USER_FAIL = "ADMIN_DELETE_USER_FAIL",
}


